### ISSUE TITLE
Regarding the application of LoRA to the transformers

### ISSUE THREAD

**Issue by ArchchanaKugathasan** [center-for-humans-and-machines/transformer-heads#10]
![image](https://github.com/user-attachments/assets/1afbd613-a3e5-4b7d-a0b2-0a5ee121531a)

In the system diagram its shown as LoRA is applied for each transformer block. But inside the transformer block which layers are applied with LoRA according to your script provided? Is it Multi-Head Attention? or Feedforward? or both? Could you explain this.

**Comment by yannikkellerde** [comment]
create_qlora with heads[ accepts a LoraConfig](https://github.com/center-for-humans-and-machines/transformer-heads/blob/a71c3949d6f3c51f3038992805c334e9aad79cca/transformer_heads/util/load_model.py#L220). 

In that one, you can specify target_modules to select for which parameters you want to train LoRA weights. Check [here](https://www.reddit.com/r/LocalLLaMA/comments/15sgg4m/what_modules_should_i_target_when_training_using/) for some more info. A common choices for LLaMA based models is [q_proj, v_proj], e.g. the projection layers of query and value for the attention mechanism.

By default (when target_modules is None), transformer heads will train LoRA parameters for [all linear layers](https://github.com/center-for-humans-and-machines/transformer-heads/blob/a71c3949d6f3c51f3038992805c334e9aad79cca/transformer_heads/util/load_model.py#L266). This is architecture-independently usually a reasonable choice that will include a few more layers than the query and value proejction, but not for example normalization parameters of a LayerNorm layer.

It can be useful to list all named paramters of your transformer head model to get a better understanding:

```python
for name, param in model.named_parameters():
    print(name)
```

There you will see that added Lora Parameters which have Lora_A and Lora_B in their name.

**Comment by ArchchanaKugathasan** [comment]
Thanks a lot for the detailed explanation! :)
