### ISSUE TITLE
Problems when evaluating model with `load_headed()`

### ISSUE THREAD

**Issue by mightymai** [center-for-humans-and-machines/transformer-heads#12]
Hi,

Thank you for your work!
I am running the notebook `text_classification_full_finetune.ipynb` on a gpu (NVIDIA GeForce RTX 3090).

But when trying to get predictions (`get_some_preds()`) or evaluate the model (`evaluate_head_wise()`) I get the following error:

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)`

I did not change any code in the notebook. The notebook` joint_multitask_learning.ipynb` works perfectly for mer, I can do evaluations. But somehow the full finetuning does not work for me. Do you have any idea why this is happening?

Thank you in advance!

**Comment by mightymai** [comment]
To be honest, I'm not entirely sure how I solved this. Maybe try `device_map=None` when loading the model using `load_headed()`. And it might have had something to do with the torch version. Maybe try updating torch (as well as transformers and accelerate). 
Hope this works!

**Comment by smirkun** [comment]
Thanks! I ended up having to modify `evaluate.py` directly, which was changing the data loader's device: #22. (Sorry, forgot to put an update here!)
