### ISSUE TITLE
Question regarding output_activation="linear" 

### ISSUE THREAD

**Issue by ArchchanaKugathasan** [center-for-humans-and-machines/transformer-heads#13]
HeadConfig(
        name=f"num_tokens_regression",
        layer_hook=-7,
        hidden_size=128,  # MLP hidden size
        num_layers=3,  # 2 hidden layers in MLP
        in_size=hidden_size,
        output_activation="linear",
        is_causal_lm=False,
        pred_for_sequence=False,
        loss_fct="mse",
        num_outputs=1,
        is_regression=True,
        loss_weight=0.0002,
    )
    
In the above configuration from one of your scripts (joint_multitask_learning.ipynb) , it is defined as 
num_layers = 3 
output_activation="linear" 
num_outputs=1

1. Here, does output_activation (linear) apply only to the last layer (output layer) in the transformer head? 
or does it mean linear activation is applied for all the layers (3 layers) including the hidden layers in the transformer head?

2. Where do you define the linear activation in the transformer head code?

**Comment by yannikkellerde** [comment]
So linear commonly means "no activation". So it is defined in this [activation_map](https://github.com/center-for-humans-and-machines/transformer-heads/blob/478dd4dbebd2217b07cdcacd786e037603082eea/transformer_heads/constants.py#L13) which is used in [MLPHead](https://github.com/center-for-humans-and-machines/transformer-heads/blob/478dd4dbebd2217b07cdcacd786e037603082eea/transformer_heads/model/head.py#L59)

Output activation only specifies the activation after the last layer. I.e. it specifies your output format (linear for any real number, sigmoid for 0-1 and ReLU for positive number)

The hidden activation is currently [hard-coded to ReLU](https://github.com/center-for-humans-and-machines/transformer-heads/blob/478dd4dbebd2217b07cdcacd786e037603082eea/transformer_heads/model/head.py#L58). I guess I do not know many situations where one benefits significantly from using something else.

**Comment by yannikkellerde** [comment]
Yes, exactly correct.

**Comment by ArchchanaKugathasan** [comment]
Thank you :)
