### ISSUE TITLE
Example for Regression Prediction

### ISSUE THREAD

**Issue by cccsurrey** [center-for-humans-and-machines/transformer-heads#2]
Hi, 

Please provide the example on how to decode for a regression task when inferencing. It does not seem like a trained regression head can provide a valid answer with the method get_top_n_preds().

Thanks

**Comment by yannikkellerde** [comment]
get_top_n_preds is only used for classification and does not really make sense for regression. E.g. get_top_n_preds will give you the n most likely classes (tokens) for a classification head while for a regression head you are just predicting a number/vector.

To use a regression model for inference, just run
```python
outputs = model(**batch)
```
where batch contains your input_ids etc.
Then outputs will be of type [HeadedModelOuput](https://github.com/center-for-humans-and-machines/transformer-heads/blob/main/transformer_heads/output.py). To get the prediction of your regression head you can thus do:
```python
regression_pred = outputs.preds_by_head["name_of_your_regression_head"]
```

**Comment by yannikkellerde** [comment]
So, I guess you are mainly talking about this line:
```python
final_value_tensor = mean_regression_tensor[0, -1, 0]
```
With the 0 in dimension 0 you select the batch dimension, with the -1 for dimension 1 you select the regression output for the last token. With the 0 in dimension 2, you select the first value of the output regression vector (Which is only 1 element as you only have a single regression output).

I think you may be confused about why you have to select -1 in dimension 1? There are two modes of doing regression with transformer heads. One is to predict a number for each input token and one is to predict only one number for the whole sequence. You can control this by setting [pred_for_sequence](https://github.com/center-for-humans-and-machines/transformer-heads/blob/58c2f201e845eb6c706c23902611082181e0264e/transformer_heads/config.py#L51C5-L51C46) in the head_config (Default is False (predict number for each input token)).

**Comment by cccsurrey** [comment]
Thank you for your information. I believe I set my HeadConfig correctly but I cannot see a single value output by inferencing with your method. 

```
head_configs = [
    HeadConfig(
        name=f"mean_regression",
        layer_hook=-7,
        in_size=hidden_size,
        output_activation="linear", #Applicable for Regression task
        is_causal_lm=False,
        pred_for_sequence=True,
        loss_fct="mse",
        num_outputs=1,  # Single value (mean)
        is_regression=True,
        loss_weight=0.002,
    ),
```
