### ISSUE TITLE
Multiple GPU support for finetuning

### ISSUE THREAD

**Issue by rushabh31** [center-for-humans-and-machines/transformer-heads#6]
@yannikkellerde, Thank you so much for creating this amazing package—it's incredibly useful. I was wondering if there's any way to leverage multiple GPUs for fine-tuning the model using this package?

**Comment by yannikkellerde** [comment]
Well, there I do not think that there is anything stopping you in principle from fine-tuning transformer-heads models using multiple gpus. I myself have sucessfully done some DDP (Distributed Data Parallel) training of transformer-heads models with multiple GPUs. For more advanced stuff such as FSDP I recommend checking out some of the existing libraries for multi-gpu training (there are a lot) and modifying their code to load transformer-heads models.

In the transformer-heads library itself I do not plan to include anything about multi-gpu training as I think other libraries serve that purpose better.

**Comment by rushabh31** [comment]
@yannikkellerde Thank you very much for your response. I'm quite new to this field, and I'd appreciate any suggestions for libraries that I could explore. Additionally, would it be possible to include an example notebook for DDP training with transformer-heads in this repository?

**Comment by yannikkellerde** [comment]
DDP really does not require any effort from your side. [Accelerate](https://huggingface.co/docs/accelerate/en/index) and Huggingfaces Trainer basically handles all that stuff for you.

If you actually want to run bigger models using e.g. FSDP / [Deepspeed ](https://github.com/microsoft/DeepSpeed) I'd recommend learning about it without transformer-heads first. It can be quite a hassle to get going.
