### ISSUE TITLE
GPT 2 finetuning notebook giving error at model loading

### ISSUE THREAD

**Issue by mandeep511** [center-for-humans-and-machines/transformer-heads#9]
[GPT2 finetuning](https://github.com/center-for-humans-and-machines/transformer-heads/blob/33a0ab25828a2c54eced73b4f816341b4345a53b/notebooks/gpt2/text_classification_full_finetune.ipynb) notebook is giving error when loading the mode:

AttributeError: 'NoneType' object has no attribute '_parameters'sendSend messageChecking who can access file19:16

![WhatsApp Image 2024-10-18 at 19 23 23_878db0b6](https://github.com/user-attachments/assets/4af7fd77-7c55-4b14-8c97-1332ebf2265c)

**Comment by yannikkellerde** [comment]
This kind of error was mentioned before by #8 . For him it kind of fixed itself from what he said. Unfortunately, I have never been able to reproduce it. I just ran the notebook you referenced and it ran just fine.

If I had to guess, it could have something to do with an older torch / transformers version.
